name: 'Get JIRA tickets out of a GitHub Release'
description: 'This action will enable you to get all JIRA tickets out of a GitHub release's included PRs'
inputs:
  repo:
    description: 'Repository to get release from'
    required: true
    default: ''
  PAT:
    description: 'Personal access token with read access to the repositories releases'
    required: true
    default: ''
outputs:
  jiraTickets: # id of output
    description: 'The tickets mentioned in the description of the PRs'
runs:
  using: 'node16'
  main: 'index.js'